# Site settings
title: "Science! So what, who cares!?"
email: "sciencesowhatwhocares@gmail.com"
description: "The simplest and fastest way to find information about the frontier of science."
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
url: "sciencesowhatwhocares.xyz" # name of site e.g. localhost:4000
relative_permalinks: true
twitter_username: sciencesowhat
github_username:  sciencesowhat

# Optionals
disqus_shortname: "sciencesowhat"
google_analytics: "UA-2345677-9"

# Build settings
markdown: redcarpet
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
